from app.models import DatasetVersion, EC2Pricing, InstanceCatalog, RegionCatalog, StoragePricing


def seed_api_data(session) -> int:
    dataset = DatasetVersion(
        source_name="seed",
        dataset_kind="pricing",
        version_label="api-v1",
        imported_row_count=1,
        source_row_count=1,
        rejected_row_count=0,
    )
    session.add(dataset)
    session.add(RegionCatalog(region_code="eu-west-1", region_name="EU (Ireland)"))
    session.add(InstanceCatalog(instance_type="m5.large", family="General purpose", vcpu=2, memory_gb=8))
    session.flush()
    session.add(
        EC2Pricing(
            dataset_version_id=dataset.id,
            instance_type="m5.large",
            region_code="eu-west-1",
            hourly_price=0.096,
            currency="USD",
            unit="Hrs",
            operating_system="Linux",
            tenancy="Shared",
            preinstalled_software="NA",
            capacity_status="Used",
        )
    )
    session.add(
        StoragePricing(
            dataset_version_id=dataset.id,
            region_code="eu-west-1",
            storage_type="gp3",
            volume_type="General Purpose",
            price_per_gb_month=0.088,
            currency="USD",
            unit="GB-Mo",
            usage_type="EU-EBS:VolumeUsage.gp3",
        )
    )
    session.commit()
    return dataset.id


def test_health_ok(client) -> None:
    response = client.get("/health")
    assert response.status_code == 200
    assert "status" in response.json()


def test_config_returns_catalog(client, session) -> None:
    seed_api_data(session)
    response = client.get("/config")
    assert response.status_code == 200
    body = response.json()
    assert body["regions"][0]["region_code"] == "eu-west-1"
    assert body["instances"][0]["instance_type"] == "m5.large"


def test_create_and_list_scenario(client) -> None:
    create_response = client.post(
        "/scenarios",
        json={
            "scenario_name": "Saved Scenario",
            "avg_cpu_usage": 1.0,
            "peak_cpu_usage": 1.5,
            "runtime_hours": 48,
            "region_code": "eu-west-1",
            "storage_type": "gp3",
            "storage_gb": 80,
            "objective_type": "balanced",
        },
    )
    assert create_response.status_code == 201

    response = client.get("/scenarios")
    assert response.status_code == 200
    body = response.json()
    assert len(body) == 1
    assert body[0]["scenario_name"] == "Saved Scenario"


def test_delete_scenario_and_runs(client, session) -> None:
    dataset_id = seed_api_data(session)
    recommendation_response = client.post(
        "/recommendations",
        json={
            "scenario_name": "Delete Me",
            "avg_cpu_usage": 1.0,
            "peak_cpu_usage": 1.5,
            "runtime_hours": 48,
            "region_code": "eu-west-1",
            "storage_type": "gp3",
            "storage_gb": 80,
            "objective_type": "balanced",
            "dataset_version_id": dataset_id,
        },
    )
    assert recommendation_response.status_code == 200
    scenario_id = recommendation_response.json()["scenario_id"]
    run_id = recommendation_response.json()["run_id"]

    delete_response = client.delete(f"/scenarios/{scenario_id}")
    assert delete_response.status_code == 200
    assert delete_response.json()["ok"] is True

    scenarios_response = client.get("/scenarios")
    assert scenarios_response.status_code == 200
    assert scenarios_response.json() == []

    run_response = client.get(f"/runs/{run_id}")
    assert run_response.status_code == 404


def test_hide_run_generated_scenarios(client, session) -> None:
    dataset_id = seed_api_data(session)
    response = client.post(
        "/recommendations",
        json={
            "scenario_name": "Generated By Run",
            "avg_cpu_usage": 1.0,
            "peak_cpu_usage": 1.5,
            "runtime_hours": 48,
            "region_code": "eu-west-1",
            "storage_type": "gp3",
            "storage_gb": 80,
            "objective_type": "balanced",
            "dataset_version_id": dataset_id,
        },
    )
    assert response.status_code == 200

    scenarios_response = client.get("/scenarios")
    assert scenarios_response.status_code == 200
    assert scenarios_response.json() == []


def test_recommendations_return_ranked_results(client, session) -> None:
    dataset_id = seed_api_data(session)
    response = client.post(
        "/recommendations",
        json={
            "scenario_name": "API Benchmark",
            "avg_cpu_usage": 1.0,
            "peak_cpu_usage": 1.5,
            "runtime_hours": 48,
            "region_code": "eu-west-1",
            "storage_type": "gp3",
            "storage_gb": 80,
            "objective_type": "cost",
            "dataset_version_id": dataset_id,
        },
    )
    assert response.status_code == 200
    body = response.json()
    assert body["scenario"]["region_code"] == "eu-west-1"
    assert len(body["results"]) == 1
    assert body["results"][0]["instance_type"] == "m5.large"


def test_run_detail_returns_saved_run(client, session) -> None:
    dataset_id = seed_api_data(session)
    create_response = client.post(
        "/recommendations",
        json={
            "scenario_name": "Run Detail Check",
            "avg_cpu_usage": 1.0,
            "peak_cpu_usage": 1.5,
            "runtime_hours": 48,
            "region_code": "eu-west-1",
            "storage_type": "gp3",
            "storage_gb": 80,
            "objective_type": "balanced",
            "dataset_version_id": dataset_id,
        },
    )
    assert create_response.status_code == 200
    run_id = create_response.json()["run_id"]

    response = client.get(f"/runs/{run_id}")
    assert response.status_code == 200
    body = response.json()
    assert body["run_id"] == run_id
    assert body["scenario"]["scenario_name"] == "Run Detail Check"
    assert body["results"][0]["instance_type"] == "m5.large"
